eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka01.com:8001/eureka,http://eureka02.com:8002/eureka
  instance:
    instance-id: cloud-pay8083
    prefer-ip-address: true
server:
  port: 8083
spring:
  application:
    name: pgsainia-provider-pay-cloud
